### PR TITLE
Update Sample PNG and Variable Name 

### PR DESCRIPTION
**Pull request by prupani-7**
## Description

PR aimed at updating PNG file name and a variable name, caused by:

- SV build error - "display-clusters" does not include a "display-clusters.png" file. Sample not copied.
- Compilation error in sample build: "Unresolved Reference" to "initialSliderValue."
Possibly due to a rebase. [PR](https://github.com/Esri/arcgis-maps-sdk-kotlin-samples/commit/9f07b9cd3270ff620f528522be10c4bcf240e491#diff-43e41faf3b4fab9118a37b0e4cdc8f635698ef4c6ddef25d4b2d1256c77c9159)

## Links and Data

Sample Epic: `runtime/kotlin/issues/3805`

## What To Review
- Files associated with this pull request.
- The sample viewer compiles successfully on a local environment.
- Please disregard the metadata checker error; have prioritized display-clusters.png to be the first image in the SV app display, not necessarily alphabetically.

## How to Test

Run the sample on the sample viewer or the repo.

### CODE REVIEW

**Comment by shubham7109** [comment]
On running a sample viewer build with `v.next` merged to this branch I see the error:
```Console
Execution failed for task ':samples-lib:compileReleaseJavaWithJavac'.
> Could not resolve all files for configuration ':samples-lib:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /Users/shu11698/Library/Android/sdk/platforms/android-34/core-for-system-modules.jar.
         > jlink executable /Users/shu11698/Library/Java/JetBrainsRuntime/jbr_jcef-17.0.7-osx-aarch64-b829.14/Contents/Home/bin/jlink does not exist.
```

I think there is an issue with my JDK while building on Gradle `8.2`. Do you see this on your end as well? @prupani-7 @ruiqima If you're able to build, could you help verify if it builds successfully?

**Review by ruiqima — APPROVED** [review]
Sample viewer can be built successfully. Thanks for the changes @prupani-7

**Comment by ruiqima** [comment]
I am able to build the release build of sample viewer, @shubham7109. Did you encounter this error while assembling the release build? It seems to be an environment settings related error.

**Comment by prupani-7** [comment]
> If you're able to build, could you help verify if it builds successfully?

SV builds successfully for me debug and release.

The error you got says
`/Users/shu11698/Library/Java/JetBrainsRuntime/jbr_jcef-17.0.7-osx-aarch64-b829.14/Contents/Home/bin/jlink does not exist.`
I am assuming you JDK is set to 17..
Does removing the .gradle, .idea and /build folders help before running the build command?

**Review by shubham7109 — APPROVED** [review]
A JDK home change to the right path worked for me, thanks for confirming 👍

**Comment by prupani-7** [comment]
Appreciate the quick reviews, @ruiqima and @shubham7109 👍

**Pull request merged**
