### PR TITLE
Update analyze hotspots

### PR DESCRIPTION
**Pull request by prupani-7**
## Description

PR to revisit sample to reflect new changes in Kotlin toolkit.

## Links and Data

Kotlin issue #3580

## What To Review

- [ ] Build and run the sample to check for any errors.
- [ ] Remove MapViewpointOperation from MapView composable. https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/pull/316
- [ ] Update the MapViewModel to be able to work with the geo-compose module.
- [ ] Update Toolkit version.
- [ ] Add the line to the "Additional information section": This sample uses the GeoCompose Toolkit module to be able to implement a Composable MapView.
- [ ] Replace the application parameter from the MainScreen with the use of LocalContext.current.applicationContext 
- [ ] Add the tags: geocompose, tookit
- [ ] Update the sample's metadata.json file to reflect file and tags changes

## How to Test

Run the sample on the sample viewer or the repo.

### CODE REVIEW

**Review by ruiqima — APPROVED** [review]
LGTM 👍

**Comment by ruiqima** [comment]
Could we update `geoprocessingJobProgress.value` to `geoprocessingJobProgress.intValue` in ViewModel class line 121  and 122?

**Comment by prupani-7** [comment]
> Could we update `geoprocessingJobProgress.value` to `geoprocessingJobProgress.intValue` in ViewModel class line 121 and 122?

I believe we can use `intValue` in place of `value`, as looking at the SnapshotIntState.kt file, 
the interface `MutableIntState` represents a mutable integer state, and it gives access to an integer value through the `value` property, which looks like it internally corresponds to the `intValue` property.

@shubham7109 since you wrote you this implementation, are you okay with this change?

**Comment by shubham7109** [comment]
@ruiqima  It seems like a welcomed change, @prupani-7 sure! let's add it in.

**Review by shubham7109 — APPROVED** [review]

**Pull request merged**
