### PR TITLE
Next release changes

### PR DESCRIPTION
**Pull request by shubham7109**
## Description
PR to prep `v.next` for next release

This branch is updated from `main`: [Diff](https://github.com/Esri/arcgis-maps-sdk-kotlin-samples/compare/shubham/next-release-changes...main)

## Links and Data
Sample issue: [#4907](https://devtopia.esri.com/runtime/kotlin/issues/4907)

### CODE REVIEW

**Review by TADraeseke — APPROVED** [review]

**Review by TADraeseke — APPROVED** [review]
LGTM!

**Comment by shubham7109** [comment]
Apologies, I hadn't pushed the version changes yet. I built the SDK locally on the latest dependencies to plugin in the SV. I found no deprecations or concerns, and the local build ran fine. 

Ready for your review. @TADraeseke

**Review by TADraeseke — CHANGES_REQUESTED** [review]
I've had a an error from RoomDatabase
room_error

I think we probably want to enable destructive migration

**Comment by shubham7109** [comment]
@TADraeseke Ready for your review :)

**Review by TADraeseke — APPROVED** [review]
All fixed! LGTM!

**Review by rchintapalli — APPROVED** [review]

**Pull request merged**
